import type { Metadata } from "next";
import { Geist } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={geistSans.className}>
        <nav className="flex justify-center gap-8 py-6 text-lg font-bold bg-gradient-to-r from-pink-300 via-purple-300 to-indigo-400 shadow-lg mb-8 animate-fade-in">
          <Link href="/" className="hover:underline">Home</Link>
          <Link href="/about" className="hover:underline">About</Link>
          <Link href="/projects" className="hover:underline">Projects</Link>
          <Link href="/contact" className="hover:underline">Contact</Link>
        </nav>
        <main className="max-w-3xl mx-auto px-4 sm:px-8 py-8 bg-white/80 rounded-3xl shadow-2xl border border-purple-200 animate-fade-in">
          {children}
        </main>
      </body>
    </html>
  );
}
